name: Test

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install c libion
        run: sudo ./build/install_libion.sh

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.5'

      - name: go mod tidy
        run: go mod tidy

      - name: run test build
        run: go test -v ./...
